### ISSUE TITLE
Our GitHub Actions assume Cargo.lock exists

### ISSUE THREAD

**Issue by jameysharp** [non-binary/http-cache-semantics#7]
According to https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html a library should not keep `Cargo.lock` in version control, but the newly updated GitHub Actions assume there is one and fail when it's missing. How should that work?

**Comment by zkat** [comment]
I think you should check in the Cargo.lock anyway -- it'll make CI run faster and allow caching. Otherwise, we can just remove the caching code altogether. Fwiw I enable cargo lock on all my libraries

**Comment by jameysharp** [comment]
Okay, hmm.

- Downstream consumers of the library will ignore its `Cargo.lock` so there's no harm to them.
- CI won't catch if there's a new release of one of our dependencies that breaks our build. On the other hand, CI only runs on pull requests and such, where that kind of breakage should usually be unrelated to whatever the contributor was actually trying to do, so these CI failures would be false alarms in a sense.
- Build time for this library is currently fast and I suspect it will remain fast, so caching in CI is nice but I don't _think_ it's important.
- Keeping `Cargo.lock` in version control goes against consensus advice from the Rust community.

I don't know what conclusion to draw here. I think reasonable people could disagree about what to prioritize among these points. I guess I'm fine with your suggestion? Apparently I have excessive respect for authority in this case or something :sweat_smile:

**Comment by zkat** [comment]
Let's just drop the caching, then :)

Do you mind doing it? It's just removing the cache save and restore sections

**Comment by jameysharp** [comment]
Can do! I think! Probably. Let's find out!

**Comment by jameysharp** [comment]
Yay, now CI only fails because the tests fail, which… is what they're there for, at the moment :sweat_smile:
